const HardwareActionTypes = {
  FETCH_HARDWARE_START: 'FETCH_HARDWARE_START',
  FETCH_HARDWARE_SUCCESS: 'FETCH_HARDWARE_SUCCESS',
  FETCH_HARDWARE_FAILURE: 'FETCH_HARDWARE_FAILURE',
};

export default HardwareActionTypes;
